---
substitutions:
  wifi_reboot_timeout: 5min

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: $wifi_reboot_timeout
  ap:
    ssid: ${device_name}-fb
    password: !secret ap_password
