---
substitutions:
  project_name: hsbne
  project_version: 1.0.0

esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  project:
    name: ${project_name}
    version: ${project_version}

packages:
  esphome: !include common/esphome.yaml
  wifi: !include common/wifi.yaml
  ota: !include common/ota.yaml
  sensors: !include common/sensors.yaml
  binary_sensors: !include common/binary_sensors.yaml
  time: !include common/time.yaml
  logger: !include common/logger.yaml
  api: !include common/api.yaml
  mdns: !include common/mdns.yaml
